server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    discovery:  # Habilitaci칩n del Discovery Client para el descubrimiento de servicios
        enabled: true
    gateway:
      routes:  # Definici칩n de rutas del gateway
        - id: estudiantes
          uri: 'http://localhost:8090'  # Uso del nombre del servicio para routing din치mico
          predicates:
            - Path=/api/student/**
        - id: cursos
          uri: 'http://localhost:9090'  # Uso del nombre del servicio para routing din치mico
          predicates:
            - Path=/api/course/**
# Registro del cliente Eureka deshabilitado (si no usas Eureka)
eureka:
  client:
    register-with-eureka: false